//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub mod prelude;

pub mod order_assigned;
pub mod order_delivered;
pub mod order_group;
pub mod order_payed;
pub mod order_queued;
pub mod order_ready;
pub mod orders;
pub mod price;
